version: "3.7"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./backend:/app
      - /app/node-modules
    command: >
      npm start
  db:
    image: mysql:8.0.12
    ports:
      - "3307:3306"
    env_file:
      - .env.-db
    restart: on-failure
    volumes:
      - ./mysql:/var/lib/mysql
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./frontend:/usr/share/ngimx/html
      - ./nginx.cong:/etc/nginx/conf.d/default.conf

